# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake

# The command to remove a file.
RM = /nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/workspace/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/nix/store/q1nssraba326p2kp6627hldd2bhg254c-cmake-3.29.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/workspace/build/CMakeFiles /home/runner/workspace/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/workspace/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flare_interpreter

# Build rule for target.
flare_interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flare_interpreter
.PHONY : flare_interpreter

# fast build rule for target.
flare_interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/build
.PHONY : flare_interpreter/fast

error_handler.o: error_handler.cpp.o
.PHONY : error_handler.o

# target to build an object file
error_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/error_handler.cpp.o
.PHONY : error_handler.cpp.o

error_handler.i: error_handler.cpp.i
.PHONY : error_handler.i

# target to preprocess a source file
error_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/error_handler.cpp.i
.PHONY : error_handler.cpp.i

error_handler.s: error_handler.cpp.s
.PHONY : error_handler.s

# target to generate assembly for a file
error_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/error_handler.cpp.s
.PHONY : error_handler.cpp.s

flare_interpreter.o: flare_interpreter.cpp.o
.PHONY : flare_interpreter.o

# target to build an object file
flare_interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/flare_interpreter.cpp.o
.PHONY : flare_interpreter.cpp.o

flare_interpreter.i: flare_interpreter.cpp.i
.PHONY : flare_interpreter.i

# target to preprocess a source file
flare_interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/flare_interpreter.cpp.i
.PHONY : flare_interpreter.cpp.i

flare_interpreter.s: flare_interpreter.cpp.s
.PHONY : flare_interpreter.s

# target to generate assembly for a file
flare_interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/flare_interpreter.cpp.s
.PHONY : flare_interpreter.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/main.cpp.s
.PHONY : main.cpp.s

memory_manager.o: memory_manager.cpp.o
.PHONY : memory_manager.o

# target to build an object file
memory_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/memory_manager.cpp.o
.PHONY : memory_manager.cpp.o

memory_manager.i: memory_manager.cpp.i
.PHONY : memory_manager.i

# target to preprocess a source file
memory_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/memory_manager.cpp.i
.PHONY : memory_manager.cpp.i

memory_manager.s: memory_manager.cpp.s
.PHONY : memory_manager.s

# target to generate assembly for a file
memory_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/memory_manager.cpp.s
.PHONY : memory_manager.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/parser.cpp.s
.PHONY : parser.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/utils.cpp.s
.PHONY : utils.cpp.s

variable.o: variable.cpp.o
.PHONY : variable.o

# target to build an object file
variable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/variable.cpp.o
.PHONY : variable.cpp.o

variable.i: variable.cpp.i
.PHONY : variable.i

# target to preprocess a source file
variable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/variable.cpp.i
.PHONY : variable.cpp.i

variable.s: variable.cpp.s
.PHONY : variable.s

# target to generate assembly for a file
variable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flare_interpreter.dir/build.make CMakeFiles/flare_interpreter.dir/variable.cpp.s
.PHONY : variable.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... flare_interpreter"
	@echo "... error_handler.o"
	@echo "... error_handler.i"
	@echo "... error_handler.s"
	@echo "... flare_interpreter.o"
	@echo "... flare_interpreter.i"
	@echo "... flare_interpreter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory_manager.o"
	@echo "... memory_manager.i"
	@echo "... memory_manager.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... variable.o"
	@echo "... variable.i"
	@echo "... variable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

